pipeline {
    agent any

    stages {
        stage('Run Backup') {
            steps {
                sshagent(credentials: ['ec2-instance-1-ssh-cred']) {
                    withCredentials([string(credentialsId: 'ec2-instance-1-db-pass', variable: 'DB_PASS')]) {
                        sh '''
                            set -a
                            . ec2-instance-1/config.env
                            set +a
                            bash shared/backup.sh
                        '''
                    }
                }
            }
        }
    }

    post {
        failure {
            echo "Backup failed"
        }
    }
}