pipeline {
    agent any

    stages {
        stage('Run Backup') {
            steps {
                sshagent(credentials: ['production-server-pem']) {
                    withCredentials([string(credentialsId: 'indeed-db-pass', variable: 'DB_PASS')]) {
                        sh '''
                            set -a
                            . indeedinspiringwebsite/config.env
                            set +a
                            bash shared/backup.sh
                        '''
                    }
                }
            }
        }
    }

    post {
        failure {
            echo "Backup failed"
        }
    }
}